blank_issues_enabled: false
contact_links:
  - name: ⚠ Feature request
    url: https://github.com/Tyrrrz/.github/blob/prime/docs/project-status.md
    about: Sorry, but this project is in maintenance mode and currently doesn't accept new feature requests.
  - name: 📖 Documentation
    url: https://github.com/Tyrrrz/DiscordChatExporter/blob/prime/.docs
    about: Find usage guides and frequently asked questions.
  - name: 🗨 Discussions
    url: https://github.com/Tyrrrz/DiscordChatExporter/discussions/new
    about: Ask and answer questions.
  - name: 💬 Discord server
    url: https://discord.gg/2SUWKFnHSm
    about: Chat with the project community.
