name: Docker CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Get release version
        id: get_version
        uses: dawidd6/action-get-tag@v1

      - name: Login
        run: docker login -u tyrrrz -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: docker build -t tyrrrz/discordchatexporter:${{ steps.get_version.outputs.tag }} -t tyrrrz/discordchatexporter:stable .

      - name: Deploy (version)
        run: docker push tyrrrz/discordchatexporter:${{ steps.get_version.outputs.tag }}

      - name: Deploy (stable)
        run: docker push tyrrrz/discordchatexporter:stable